// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZEX69AO7GzpKti0rirDSDQXZG-ue06w',
    appId: '1:204617251938:web:bde6085508e530c0bd653b',
    messagingSenderId: '204617251938',
    projectId: 'flutter-map-248ae',
    authDomain: 'flutter-map-248ae.firebaseapp.com',
    storageBucket: 'flutter-map-248ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eEN6xIvke7922YpD1WZ1MneiCQBLHrY',
    appId: '1:204617251938:android:1f52797afa936c8fbd653b',
    messagingSenderId: '204617251938',
    projectId: 'flutter-map-248ae',
    storageBucket: 'flutter-map-248ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtlCscVJ6pnbLkElvyH1qZ2MjRK2_W5U',
    appId: '1:204617251938:ios:38e394d2ca4e0e30bd653b',
    messagingSenderId: '204617251938',
    projectId: 'flutter-map-248ae',
    storageBucket: 'flutter-map-248ae.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrtlCscVJ6pnbLkElvyH1qZ2MjRK2_W5U',
    appId: '1:204617251938:ios:fa2b43bfe78225fabd653b',
    messagingSenderId: '204617251938',
    projectId: 'flutter-map-248ae',
    storageBucket: 'flutter-map-248ae.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
